// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateLocalTerminal(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function CreateSSHTerminal(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFromKeychain(arg1:string):Promise<void>;

export function DuplicateTerminal(arg1:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppDataPath():Promise<string>;

export function GetBackupPath():Promise<string>;

export function GetDatabasePath():Promise<string>;

export function GetFromKeychain(arg1:string):Promise<string>;

export function GetGuestConfigPath():Promise<string>;

export function GetGuestSnippetsPath():Promise<string>;

export function GetTerminalMetadata(arg1:string):Promise<terminal.SessionMetadata>;

export function GetUserConfigPath(arg1:string):Promise<string>;

export function GetUserSnippetsPath(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveToKeychain(arg1:string,arg2:string):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ShowOpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function ShowSaveFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
