// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateLocalTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLocalTerminal'](arg1, arg2, arg3);
}

export function CreateSSHTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSSHTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFromKeychain(arg1) {
  return window['go']['main']['App']['DeleteFromKeychain'](arg1);
}

export function DuplicateTerminal(arg1) {
  return window['go']['main']['App']['DuplicateTerminal'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAppDataPath() {
  return window['go']['main']['App']['GetAppDataPath']();
}

export function GetBackupPath() {
  return window['go']['main']['App']['GetBackupPath']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetFromKeychain(arg1) {
  return window['go']['main']['App']['GetFromKeychain'](arg1);
}

export function GetGuestConfigPath() {
  return window['go']['main']['App']['GetGuestConfigPath']();
}

export function GetGuestSnippetsPath() {
  return window['go']['main']['App']['GetGuestSnippetsPath']();
}

export function GetTerminalMetadata(arg1) {
  return window['go']['main']['App']['GetTerminalMetadata'](arg1);
}

export function GetUserConfigPath(arg1) {
  return window['go']['main']['App']['GetUserConfigPath'](arg1);
}

export function GetUserSnippetsPath(arg1) {
  return window['go']['main']['App']['GetUserSnippetsPath'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveToKeychain(arg1, arg2) {
  return window['go']['main']['App']['SaveToKeychain'](arg1, arg2);
}

export function ShowMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2, arg3);
}

export function ShowOpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowOpenFileDialog'](arg1, arg2);
}

export function ShowSaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowSaveFileDialog'](arg1, arg2, arg3);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
