// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFromKeychain(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppDataPath():Promise<string>;

export function GetBackupPath():Promise<string>;

export function GetDatabasePath():Promise<string>;

export function GetFromKeychain(arg1:string):Promise<string>;

export function GetGuestConfigPath():Promise<string>;

export function GetUserConfigPath(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveToKeychain(arg1:string,arg2:string):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ShowOpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function ShowSaveFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
